Create language_pu-in.properties
xEdziu/KeepMyPassword-Desktop pull request #142
Opened 2022-10-21 11:24 UTC by anupeshverma

2022-10-21 11:24 UTC, anupeshverma commented
Please accept the Pr and label as hacktoberfest

2022-10-25 13:20 UTC, AshishSharma1203 commented
@xEdziu  is this translation completed or can i work upon this ??? Because the PR hasn't been merged yet.

2022-10-25 14:06 UTC, xEdziu commented
@AshishSharma1203 hi, I've quite busy recently, I will work on this repo today

2022-10-25 14:27 UTC, xEdziu requested changes
Do not seperate add spaces (blanks) between key and value

2022-10-25 14:27 UTC, xEdziu commented on src/main/resources/language_pu-in.properties
> +adding.new.password=Adding new password
Not translated line

2022-10-25 14:27 UTC, xEdziu commented on src/main/resources/language_pu-in.properties
> +appName=ਮੇਰਾ ਪਾਸਵਰਡ ਰੱਖੋ
Keep ```appName``` key as given in Guide for Translators in wiki section :)

2022-10-25 15:37 UTC, AshishSharma1203 commented
> @AshishSharma1203 hi, I've been quite busy recently, I will work on this repo today

It's okkayy sir. 
@anupeshverma  has already worked upon this. So , its better he will make the required changes (if soo) . I can work upon another issue.

2022-10-25 19:05 UTC, xEdziu approved these changes
Now everything is okay!

2022-10-25 19:06 UTC, xEdziu commented
I have one question, what language is that? @anupeshverma

2022-10-25 19:18 UTC, anupeshverma commented
Its Punjabi language spoken in Punjab state of India

2022-10-28 07:36 UTC, merged